cargo-features = ["profile-rustflags"]

[profile.release]
opt-level = 3
lto = "fat"
rustflags = ["-Z", "share-generics=y"]

[package]
name = "oxeylyzer"
version = "0.1.0"
authors = ["O_X_E_Y <lucoerlemans37@gmail.com>"]
edition = "2021"

[workspace]
members = [
    "oxeylyzer-core",
    "oxeylyzer-repl"
]

[dependencies]
oxeylyzer-core = { path = "./oxeylyzer-core" }
oxeylyzer-repl = { path = "./oxeylyzer-repl" }

[[bin]]
name = "oxeylyzer"
path = "./oxeylyzer-repl/src/bin/main.rs"